---
settings:
  name: ONTAP tools for VMware vSphere 10.2
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: 适用于VMware vSphere 10.2的ONTAP工具文档
    url: "/index.html"
  - section: release-notes
  - section: concepts
  - section: deploy
  - section: configure
  - section: protect
  - section: manage
  - section: upgrade
  - section: recover
  - section: migrate
  - section: automation
  - title: 法律声明
    url: "/legal-notices.html"
