---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: migrate 
summary: 迁移存储数据时、系统会使用REST API手动启用存储后端。迁移VASA提供程序数据时、数据会从现有Derby数据库导出并导入到MongoDB数据库中。 
---
= 从适用于VMware vSphere 9.x的ONTAP工具迁移到10.2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
迁移存储数据时、系统会使用REST API手动启用存储后端。迁移VASA提供程序数据时、数据会从现有Derby数据库导出并导入到MongoDB数据库中。


NOTE: 建议仅在适用于VMware vSphere 9.x的ONTAP工具设置仅用于提供vasa提供程序功能时才迁移此设置。


NOTE: 从适用于VMware vSphere的ONTAP工具9.x迁移到10.2后、采用NVMe/FC协议的vvol数据存储库将无法工作、因为ONTAP工具10.2仅支持对VMFS数据存储库使用NVMe-oF。

* 关于此任务 *

支持从适用于VMware vSphere 9.10D2、9.11D1、9.12D1和9.13D2的ONTAP工具迁移到10.2版。


NOTE: 如果您正在使用适用于VMware vSphere 9.13P1版本的ONTAP工具、则应先升级到9.13D2、然后再迁移到10.2版。


NOTE: 作为现有用户、在升级到修补程序版本之前、您需要从当前版本创建OVA备份。



== 常见迁移步骤

. 部署适用于VMware vSphere 10.2版的适用于ONTAP的OVA工具。
. 添加要迁移到适用于VMware vSphere 10.2版的ONTAP工具的vCenter Server实例。请参见 link:../configure/add-vcenter.html["添加vCenter Server实例"]
. 从适用于VMware vSphere插件的ONTAP工具vCenter Server API本地板载存储后端。将存储添加为本地范围的存储以进行迁移。
. 只有在触发数据存储库发现作业后、从适用于VMware vSphere 9.xx的ONTAP工具迁移的NFS和VMFS数据存储库才会显示在适用于VMware vSphere 10.2的ONTAP工具中、此作业可能需要长达30分钟才能触发。验证这些数据存储库是否显示在适用于VMware vSphere的ONTAP工具插件用户界面页面的概述页面中。




== SRA迁移步骤

* 开始之前 *

迁移前、请确保其中一个站点处于受保护状态、另一个站点处于恢复状态。


NOTE: 如果故障转移刚刚完成且重新保护处于待定状态、请勿迁移。完成重新保护、然后执行迁移。同一适用场景测试恢复计划。恢复计划测试完成后、清理测试恢复、然后开始迁移。

. 要在VMware Live Site Recovery UI中删除适用于VMware vSphere 9.xx版本SRA适配器的ONTAP工具、请执行以下步骤：
+
.. 转到VMware Live Site Recovery配置管理页面
.. 转至Storage Replication Adapter部分
.. 单击“KEBBP”菜单，然后单击“*Reset configuration*”(重置配置)
.. 点击“烤肉”菜单，然后选择*Delete*
+
在保护站点和恢复站点上执行这些步骤。



. 按照中的步骤在保护站点和恢复站点上安装适用于VMware vSphere 10.2 SRA适配器的ONTAP工具 link:../protect/configure-on-srm-appliance.html["在VMware Live Site Recovery设备上配置SRA"]
. 在VMware Live Site Recovery UI页面中，执行*Discover Arrays *和*Discover Devices*操作，并验证这些设备是否显示为迁移前的状态。




== VASA提供程序迁移步骤

. 在适用于VMware vSphere的现有ONTAP工具上启用Derby端口1527。要启用此端口、请使用root用户登录到命令行界面并运行以下命令：
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. 部署适用于VMware vSphere 10.2版的适用于ONTAP的OVA工具。
. 添加要迁移到适用于VMware vSphere 10.2版的ONTAP工具的vCenter Server实例。请参阅。 link:../configure/add-vcenter.html["添加vCenter Server实例"]
. 从远程插件vCenter Server API本地板载存储后端。将存储添加为本地范围以进行迁移。
. 问题描述要迁移的API调用：
+
[]
====
*HTTP方法和端点*

此REST API调用使用以下方法和端点。

|===


| * HTTP 方法 * | * 路径 * 


| 发布 | /api/v1 
|===
*处理类型*

异步

*卷示例*

/api/v1/vcCenters/｛vcpguid｝/migration-jobs

*JSON输入示例*从9.12和9.13迁移的请求正文：

{"OTV_IP"："10.12.13.45"、"VASA提供程序凭据"：{"USERNAME"："vasauser"、"password"："*********｝"DATABASE密码"："*********”}

其他版本迁移的请求正文：

{"OTV_IP"："10.12.13.45"、"VASA提供程序凭据"：{"USERNAME":"vasauser"、"password"*********}

*JSON输出示例*

返回作业对象。您应保存作业标识符、以便在下一步中使用。

｛"id"：123、"migration_id"：d50073ce-35b4-4c51-9d2e-4ce66f802c35"、"stats"："running"｝

====
. 使用以下URI检查状态：
+
[listing]
----
https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
+
作业完成后、验证迁移报告。您可以在JobData中查看来自作业响应的报告。

. 将适用于VMware vSphere存储提供程序的ONTAP工具添加到vCenter Server和 link:../configure/registration-process.html["将VASA Provider注册到vCenter Server"]。
. 从维护控制台停止适用于VMware vSphere存储提供程序9.10/9.11/9.12/9.13的ONTAP工具VASA Provider服务。
+
请勿删除此VASA Provider。

+
停止旧的VASA提供程序后、vCenter Server将故障转移到适用于VMware vSphere的ONTAP工具。所有数据存储库和VM均可通过适用于VMware vSphere的ONTAP工具访问和提供服务。

. 使用以下API执行修补程序迁移：
+
[]
====
*HTTP方法和端点*

此REST API调用使用以下方法和端点。

|===


| * HTTP 方法 * | * 路径 * 


| patch | /api/v1 
|===
*处理类型*

异步

*卷示例*

修补"/api/v1/vcCenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65r7-w345-8ufdbb887d43

*JSON输入示例*

｛"id"：123、"migration_id"：d50073ce-35b4-4c51-9d2e-4ce66f802c35"、"stats"："running"｝

*JSON输出示例*

返回作业对象。您应保存作业标识符、以便在下一步中使用。

｛"id"：123、"migration_id"：d50073ce-35b4-4c51-9d2e-4ce66f802c35"、"stats"："running"｝

修补操作的请求正文为空。


NOTE: UUID是迁移后API响应中返回的迁移UUID。

修补程序迁移API成功后、所有VM都将符合存储策略。

====
. 用于迁移的删除API为：
+
[]
====
|===


| * HTTP 方法 * | * 路径 * 


| 删除 | /api/v1 
|===
*处理类型*

异步

*卷示例*

/api/v1/vcCenters/｛vcpguid｝/migration-jobs/｛migration_id｝

此API将按迁移ID删除迁移、并删除给定vCenter Server上的迁移。

====


成功迁移并将ONTAP工具10.2注册到vCenter Server后、请执行以下操作：

* 刷新所有主机上的证书。
* 请等待一段时间、然后再执行数据存储库(DS)和虚拟机(VM)操作。等待时间取决于设置中存在的主机、DS和VM的数量。如果不等待、操作可能会间歇性失败。

