---
permalink: configure/esxi-host-values.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用适用于 VMware vSphere 的 ONTAP 工具在 ESXi 主机上设置超时和其他值，以确保性能最佳并成功进行故障转移。适用于VMware vSphere的ONTAP工具设置的值基于内部NetApp测试。 
---
= 设置ESXi主机值
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用适用于 VMware vSphere 的 ONTAP 工具在 ESXi 主机上设置超时和其他值，以确保性能最佳并成功进行故障转移。适用于VMware vSphere的ONTAP工具设置的值基于内部NetApp测试。

您可以在 ESXi 主机上设置以下值：



== HBA/CNA适配器设置

为NetApp存储系统设置建议的HBA超时设置。

* * 磁盘 .QFullSampleSize*
+
对于所有配置、请将此值设置为32。设置此值有助于防止出现 I/O 错误。

* * 磁盘 .QFullThreshold *
+
对于所有配置、请将此值设置为8。设置此值有助于防止出现 I/O 错误。

* * Emulex FC HBA 超时 *
+
使用默认值。

* * QLogic FC HBA 超时 *
+
使用默认值。





== MPIO设置

MPIO设置定义NetApp存储系统的首选路径。MPIO设置可确定哪些可用路径已进行优化(与遍历互连缆线的非优化路径不同)、并将首选路径设置为其中一个路径。

在高性能环境中、或者在测试单个LUN数据存储库的性能时、请考虑将轮询(VMW_PSP_RR)路径选择策略(PSP)的负载平衡设置从默认IOPS设置1000更改为值1。



== NFS 设置

* * 网络 .TcpipHeapSize*
+
将此值设置为32。

* * 网络 .TcpipHeapMax*
+
将此值设置为1024MB。

* * 。 nfs.MaxVolumes*
+
将此值设置为256。

* *NFS41.MaxVolumes*
+
将此值设置为256。

* * 。 nfs.MaxQueueDepth*
+
将此值设置为128或更高、以避免出现队列瓶颈。

* * 。 nfs.HeartbeatMaxFailures *
+
对于所有NFS配置、请将此值设置为10。

* * 。 nfs.HeartbeatFrequency*
+
对于所有NFS配置、请将此值设置为12。

* * 。 nfs.HeartbeatTimeout*
+
对于所有NFS配置、请将此值设置为5。


