---
permalink: manage/storage-view-datastore.html 
sidebar: sidebar 
keywords: Remove vVol datastore 
summary: 适用于VMware vSphere的ONTAP工具的配置选项卡下的ONTAP存储视图可提供与数据存储库及其卷相关的数据。 
---
= 数据存储库的ONTAP存储视图
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
适用于VMware vSphere的ONTAP工具的配置选项卡下的ONTAP存储视图可提供与数据存储库及其卷相关的数据。此视图提供了数据存储库的存储端视图。



== NFS数据存储库的ONTAP存储视图

.步骤
. 从vSphere Client导航到NFS数据存储库。
. 单击右窗格中的*Config*选项卡。
. 选择* NetApp ONTAP tools*>* ONTAP Storage*。右窗格中将显示*存储详细信息*和* NFS详细信息*。
+
** 存储详细信息页面包含有关存储后端、聚合和卷的信息。
** NFS详细信息页面包含与NFS数据存储库相关的数据。






== VMFS数据存储库的ONTAP存储视图

.步骤
. 从vSphere Client导航到VMFS数据存储库。
. 单击右窗格中的*Config*选项卡。
. 选择* NetApp ONTAP tools*>* ONTAP Storage*。对于NVMe/TCP或NVMe/FC协议、右侧窗格将显示*存储详细信息*和* LUN详细信息*或*命名空间详细信息*。
+
** 存储详细信息页面包含有关存储后端、聚合和卷的信息。
** LUN详细信息页面包含与LUN相关的数据。
** 如果对VMFS数据存储库使用NVMe/TCP或NVMe/FC协议、则命名空间详细信息页面将包含与命名空间相关的数据。






== 适用于ONTAP数据存储库的VMware存储视图

.步骤
. 从vSphere Client导航到vvol数据存储库。
. 单击右窗格中的*Config*选项卡。
. 选择* NetApp ONTAP tools*>* ONTAP Storage*。
. ONTAP存储视图将列出所有卷。您可以从ONTAP存储窗格中展开或删除存储。
+
按照link:../manage/expand-storage-of-vvol-datastore.html["扩展 vVol 数据存储库"]第节中的说明添加link:../manage/remove-storage-from-a-vvols-datastore.html["缩减数据存储库"]此数据存储库、并按照第节中的说明删除此数据存储库。


